---
mysql_replication_role: "master"
mysql_server_id: 1

# MySql general log
mysql_log: "/var/log/mysql/mysql-general.log"

# Slow query log settings.
mysql_slow_query_log_enabled: yes
mysql_slow_query_time: "2"