---
apache_remove_default_vhost: true

munin_admin_user: muninadmin
munin_admin_password: muninadmin

munin_hosts:
  - {
    name: "localhost",
    address: "127.0.0.1",
    extra: ["use_node_name yes"]
  }
  - {
    name: "app",
    address: "192.168.2.80",
    extra: ["use_node_name yes"]
  }  
#Variables for munin-node configuration
#For localhost you don´t need to define the allowed-IP